/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SampleJackson;

import static org.junit.Assert.*;

import org.junit.Test;

public class SampleJacksonTest {
    @Test public void testSomeLibraryMethod() {
        SampleJackson classUnderTest = new SampleJackson();
        assertEquals("Sample!", classUnderTest.getMessage());
    }
}
