/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SampleJackson;

public class SampleJackson {
	public static void main(String[] args) {
		SampleJackson sample = new SampleJackson();
        System.out.println(sample.getMessage());
    }

    public String getMessage() {
        return "Sample!";
    }
}
